Check installation channel for operator
RedHat-SP-Security/tang-operator-tests pull request #84
Opened 2024-01-12 13:35 UTC by Koncpa

2024-01-12 14:23 UTC, sarroutbi requested changes

2024-01-12 14:23 UTC, sarroutbi commented on Plans/packit-ci.fmf
> -  TANG_IMAGE: "quay.io/sec-eng-special/fedora_tang_server"
This should be unchanged. This is the Tang image (the Tang container), not the Tang operator container

2024-01-15 08:00 UTC, Koncpa commented on Plans/packit-ci.fmf
> +  TANG_IMAGE: "quay.io/sec-eng-special/nbde-tang-server-tang-operator-bundle"
@sarroutbi  Sure, I can keep it as it is, but is it most actual version regarding to latest changes??

2024-01-19 13:18 UTC, sarroutbi commented
Hello Patrik. Are you planning to fix this?

2024-01-22 09:26 UTC, Koncpa commented
> Hello Patrik. Are you planning to fix this?

Sure, I just not focused on this PR, right now, but it should be already adjusted...

2024-01-22 11:13 UTC, sarroutbi approved these changes
Changes LGTM

2024-02-19 12:54 UTC, merged